# -----------------------------------------------------------------------------
# LightQOS - Quantum Operating System
# FUNDING.yml — GitHub Sponsors funding configuration
#
# Copyright (c) 2021 - 2026 Márcio Coutinho
# Date: 01-12-2025
# All rights reserved.
# -----------------------------------------------------------------------------

github: [marciolscoutinho]
