env:
  PYO3_USE_ABI3_FORWARD_COMPATIBILITY: "1"
name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint numpy
    - name: Analysing the code with pylint
      run: |
        pylint frontend/lightqos --disable=missing-module-docstring,missing-class-docstring,missing-function-docstring,too-few-public-methods,too-many-instance-attributes,too-many-arguments,too-many-positional-arguments,too-many-locals,too-many-branches,wrong-import-position,import-outside-toplevel,attribute-defined-outside-init,subprocess-run-check,useless-import-alias,function-redefined
